FROM ruby:4.0.1-alpine

ENV RAILS_ENV=test
ENV NODE_ENV=test

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    git \
    libpq-dev \
    yaml-dev \
    nodejs \
    yarn \
    vips-dev

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
